services:
  transformer-path-visualizer:
    build: .
    ports:
      - "62352:8000"
    # env_file allows passing all variables from .env into the container
    env_file:
      - .env
    # Volumes now use variables from the .env file!
    volumes:
      # Maps the user-defined DATA_DIR on the host to /app/data inside the container
      - ${DATA_DIR}:/app/data:z
      # Maps the user-defined MODEL_DIR on the host to /app/models inside the container
      - ${MODEL_DIR}:/app/models:z
    restart: unless-stopped
    network_mode: bridge
    command: >
      gunicorn --workers 4
               --timeout 2000
               --bind 0.0.0.0:8000 
               --log-level debug 
               --enable-stdio-inheritance 
               app:app