name: Python CI with Pytest

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' 

    - name: Install package and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . 

    - name: Test with pytest
      run: |
        pytest