name: Python CI with Pytest

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      # Install Poetry (essential first step for the new workflow)
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3 # Use the version you prefer

      # Install all project and development dependencies from pyproject.toml
      - name: Install Dependencies
        run: poetry install --no-root # '--no-root' is faster if you aren't installing the package itself

      # Run the test command within the environment managed by Poetry
      - name: Run pytest
        run: poetry run pytest
